[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino, espidf

board_build.filesystem = littlefs
monitor_speed = 115200

; 안정적인 빌드/링크 옵션
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ENABLE_BLE_PROV=1
  -D SMARTFARM_BLE_PROV=1
  ;
  -DCORE_DEBUG_LEVEL=3
  -DAPP_VERSION=\"1.0.0\"
  -DSETTINGS_SCHEMA_VERSION=1
  -DUI_TARGET_FPS=20
  -DDEVICE_LINE_ID=\"line-001\"
  -DDEVICE_BED_ID=\"bed-001\"

  ; TFT_eSPI
  -D USER_SETUP_LOADED
  -D ST7789_DRIVER

  -D TFT_WIDTH=170
  -D TFT_HEIGHT=320

  -D TFT_MOSI=11
  -D TFT_SCLK=12
  -D TFT_CS=10
  -D TFT_DC=9
  -D TFT_RST=8

  -D TFT_BL=38
  -D TFT_BACKLIGHT_ON=HIGH

  -D SPI_FREQUENCY=27000000

  -D LOAD_FONT2
  -D LOAD_FONT4

lib_ignore =
  QRCode

lib_deps =
  bodmer/TFT_eSPI@^2.5.43
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^7.0.4
  ricmoo/QRCode@^0.0.1

; ===== 선택 기능 플래그 =====
; AWS IoT TLS 사용 시(기본 OFF)
; build_flags =
;   ${env:esp32s3.build_flags}
;   -DUSE_AWS_IOT=1
;   -DENABLE_BLE_PROV=1  